mirrors/urls.py
from django.conf.urls import patterns

from .views import mirrors, status, mirror_details, url_details
from .views.api import status_json, mirror_details_json, locations_json

urlpatterns = patterns('',
    (r'^$', mirrors, {}, 'mirror-list'),
    (r'^status/$', status,  {}, 'mirror-status'),
    (r'^status/json/$', status_json,  {}, 'mirror-status-json'),
    (r'^status/tier/(?P<tier>\d+)/$', status, {}, 'mirror-status-tier'),
    (r'^status/tier/(?P<tier>\d+)/json/$', status_json, {}, 'mirror-status-tier-json'),
    (r'^locations/json/$', locations_json,  {}, 'mirror-locations-json'),
    (r'^(?P<name>[\.\-\w]+)/$', mirror_details),
    (r'^(?P<name>[\.\-\w]+)/json/$', mirror_details_json),
    (r'^(?P<name>[\.\-\w]+)/(?P<url_id>\d+)/$', url_details),
)

# vim: set ts=4 sw=4 et:

news/urls.py
from django.conf.urls import patterns
from django.contrib.auth.decorators import permission_required
from .views import (NewsDetailView, NewsListView,
        NewsCreateView, NewsEditView, NewsDeleteView)


urlpatterns = patterns('news.views',
    (r'^$', NewsListView.as_view(), {}, 'news-list'),

    (r'^preview/$', 'preview'),
    # old news URLs, permanent redirect view so we don't break all links
    (r'^(?P<object_id>\d+)/$', 'view_redirect'),

    (r'^add/$',
        permission_required('news.add_news')(NewsCreateView.as_view())),
    (r'^(?P<slug>[-\w]+)/$',
        NewsDetailView.as_view()),
    (r'^(?P<slug>[-\w]+)/edit/$',
        permission_required('news.change_news')(NewsEditView.as_view())),
    (r'^(?P<slug>[-\w]+)/delete/$',
        permission_required('news.delete_news')(NewsDeleteView.as_view())),
)

# vim: set ts=4 sw=4 et:

urls.py
from django.conf.urls import include, patterns, url
from django.contrib import admin

from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView, RedirectView

from feeds import PackageFeed, NewsFeed, ReleaseFeed

urlpatterns = []

# Public pages
urlpatterns += patterns('public.views',
    (r'^$', 'index', {}, 'index'),
    (r'^about/$', TemplateView.as_view(template_name='public/about.html'),
        {}, 'page-about'),
    (r'^art/$', RedirectView.as_view(url='https://git.hyperbola.info:50100/culture'),
        {}, 'page-art'),
    (r'^donate/$', RedirectView.as_view(url='https://wiki.hyperbola.info/Donations'),
        {}, 'page-donate'),
    (r'^download/$', RedirectView.as_view(url='https://wiki.hyperbola.info/Get_Hyperbola'),
        {}, 'page-download'),
    (r'^master-keys/$',  'keys',     {}, 'page-keys'),
    (r'^master-keys/json/$', 'keys_json', {}, 'pgp-keys-json'),
    (r'^members/(?P<slug>[-\w]+)/$', 'members', {}, 'members'),
)

# Feeds patterns, used below
feeds_patterns = patterns('',
    (r'^$',          'public.views.feeds', {}, 'feeds-list'),
    (r'^news/$',     cache_page(311)(NewsFeed())),
    (r'^packages/$', cache_page(313)(PackageFeed())),
    (r'^packages/(?P<arch>[A-z0-9]+)/$',
        cache_page(313)(PackageFeed())),
    (r'^packages/all/(?P<repo>[A-z0-9\-]+)/$',
        cache_page(313)(PackageFeed())),
    (r'^packages/(?P<arch>[A-z0-9]+)/(?P<repo>[A-z0-9\-]+)/$',
        cache_page(313)(PackageFeed())),
    (r'^releases/$', cache_page(317)(ReleaseFeed())),
)

# Includes and other remaining stuff
urlpatterns += patterns('',
    (r'^admin/',     include(admin.site.urls)),
    (r'^devel/',     include('devel.urls')),
    (r'^feeds/',     include(feeds_patterns)),
    (r'^groups/',    include('packages.urls_groups')),
    (r'^mirrorlist/',include('mirrors.urls_mirrorlist')),
    (r'^mirrors/',   include('mirrors.urls')),
    (r'^news/',      include('news.urls')),
    (r'^packages/',  include('packages.urls')),
    (r'^releng/',    include('releng.urls')),
    (r'^todo/',      include('todolists.urls')),
    (r'^visualize/', include('visualize.urls')),
    (r'^opensearch/packages/$', 'packages.views.opensearch',
        {}, 'opensearch-packages'),
    (r'^opensearch/packages/suggest$', 'packages.views.opensearch_suggest',
        {}, 'opensearch-packages-suggest'),
)

# Authentication
urlpatterns += patterns('django.contrib.auth.views',
    (r'^login/$', 'login', {'template_name': 'registration/login.html'}, 'login'),
    (r'^logout/$', 'logout', {'template_name': 'registration/logout.html'}, 'logout'),
)

# Redirects for older known pages we see in the logs
legacy_urls = (
    ('^about.php',     '/about/'),
    ('^changelog.php', '/packages/?sort=-last_update'),
    ('^devs.php',      '/members/developers/'),
    ('^donations.php', '/donate/'),
    ('^download.php',  '/download/'),
    ('^index.php',     '/'),
    ('^logos.php',     '/logotypes/'),
    ('^news.php',      '/news/'),
    ('^packages.php',  '/packages/'),
    ('^members.php',    '/members/'),
    ('^todolists/$',   '/todo/'),
    ('^developers/$',  '/members/developers/'),
    ('^artists/$',     '/members/artists/'),
    ('^fellows/$',     '/members/member-fellows/'),
    ('^trustedusers/$', '/members/trustedusers/'),

    ('^docs/en/guide/install/arch-install-guide.html',
        'https://wiki.hyperbola.info/Installation_Guide'),
    ('^docs/en/', 'https://wiki.hyperbola.info/'),
    ('^docs/', 'https://wiki.hyperbola.info/'),
)

urlpatterns += [url(old_url, RedirectView.as_view(url=new_url))
        for old_url, new_url in legacy_urls]


def show_urls(urllist=urlpatterns, depth=0):
    for entry in urllist:
        print "  " * depth, entry.regex.pattern
        if hasattr(entry, 'url_patterns'):
            show_urls(entry.url_patterns, depth + 1)

# vim: set ts=4 sw=4 et:

mirrors/models.py
from datetime import timedelta
import socket
from urlparse import urlparse

from django.core.exceptions import ValidationError
from django.db import models
from django.db.models.signals import pre_save
from django_countries.fields import CountryField

from .fields import IPNetworkField
from main.utils import set_created_field


class Mirror(models.Model):
    TIER_CHOICES = (
        (0, 'Tier 0'),
        (1, 'Tier 1'),
        (2, 'Tier 2'),
        (-1, 'Untiered'),
    )

    name = models.CharField(max_length=255, unique=True)
    tier = models.SmallIntegerField(default=2, choices=TIER_CHOICES)
    upstream = models.ForeignKey('self', null=True, on_delete=models.SET_NULL)
    admin_email = models.EmailField(max_length=255, blank=True)
    alternate_email = models.EmailField(max_length=255, blank=True)
    public = models.BooleanField(default=True)
    active = models.BooleanField(default=True)
    isos = models.BooleanField("ISOs", default=True)
    rsync_user = models.CharField(max_length=50, blank=True, default='')
    rsync_password = models.CharField(max_length=50, blank=True, default='')
    bug = models.PositiveIntegerField("Flyspray bug", null=True, blank=True)
    notes = models.TextField(blank=True)
    created = models.DateTimeField(editable=False)
    last_modified = models.DateTimeField(editable=False)

    class Meta:
        ordering = ('name',)

    def __unicode__(self):
        return self.name

    def downstream(self):
        return Mirror.objects.filter(upstream=self).order_by('name')

    def get_absolute_url(self):
        return '/mirrors/%s/' % self.name


class MirrorProtocol(models.Model):
    protocol = models.CharField(max_length=10, unique=True)
    is_download = models.BooleanField(default=True,
            help_text="Is protocol useful for end-users, e.g. HTTP")
    default = models.BooleanField(default=True,
            help_text="Included by default when building mirror list?")
    created = models.DateTimeField(editable=False)

    def __unicode__(self):
        return self.protocol

    class Meta:
        ordering = ('protocol',)


class MirrorUrl(models.Model):
    url = models.CharField("URL", max_length=255, unique=True)
    protocol = models.ForeignKey(MirrorProtocol, related_name="urls",
            editable=False, on_delete=models.PROTECT)
    mirror = models.ForeignKey(Mirror, related_name="urls")
    country = CountryField(blank=True, db_index=True)
    has_ipv4 = models.BooleanField("IPv4 capable", default=True,
            editable=False)
    has_ipv6 = models.BooleanField("IPv6 capable", default=False,
            editable=False)
    active = models.BooleanField(default=True)
    bandwidth = models.FloatField("bandwidth (mbits)", null=True, blank=True)
    created = models.DateTimeField(editable=False)

    class Meta:
        verbose_name = 'mirror URL'

    def __unicode__(self):
        return self.url

    def address_families(self):
        hostname = urlparse(self.url).hostname
        info = socket.getaddrinfo(hostname, None, 0, socket.SOCK_STREAM)
        families = [x[0] for x in info]
        return families

    @property
    def hostname(self):
        return urlparse(self.url).hostname

    def clean(self):
        try:
            # Auto-map the protocol field by looking at the URL
            protocol = urlparse(self.url).scheme
            self.protocol = MirrorProtocol.objects.get(protocol=protocol)
        except Exception as e:
            raise ValidationError(e)
        try:
            families = self.address_families()
            self.has_ipv4 = socket.AF_INET in families
            self.has_ipv6 = socket.AF_INET6 in families
        except socket.error:
            # We don't fail in this case; we'll just set both to False
            self.has_ipv4 = False
            self.has_ipv6 = False

    def get_absolute_url(self):
        return '/mirrors/%s/%d/' % (self.mirror.name, self.pk)


class MirrorRsync(models.Model):
    # max length is 40 chars for full-form IPv6 addr + subnet
    ip = IPNetworkField("IP")
    mirror = models.ForeignKey(Mirror, related_name="rsync_ips")
    created = models.DateTimeField(editable=False)

    def __unicode__(self):
        return unicode(self.ip)

    class Meta:
        verbose_name = 'mirror rsync IP'
        ordering = ('ip',)


class CheckLocation(models.Model):
    hostname = models.CharField(max_length=255)
    source_ip = models.GenericIPAddressField('source IP',
            unpack_ipv4=True, unique=True)
    country = CountryField()
    created = models.DateTimeField(editable=False)

    class Meta:
        ordering = ('hostname', 'source_ip')

    def __unicode__(self):
        return self.hostname

    @property
    def family(self):
        info = socket.getaddrinfo(self.source_ip, None, 0, 0, 0,
                socket.AI_NUMERICHOST)
        families = [x[0] for x in info]
        return families[0]

    @property
    def ip_version(self):
        '''Returns integer '4' or '6'.'''
        if self.family == socket.AF_INET6:
            return 6
        if self.family == socket.AF_INET:
            return 4
        return None


class MirrorLog(models.Model):
    url = models.ForeignKey(MirrorUrl, related_name="logs")
    location = models.ForeignKey(CheckLocation, related_name="logs", null=True)
    check_time = models.DateTimeField(db_index=True)
    last_sync = models.DateTimeField(null=True)
    duration = models.FloatField(null=True)
    is_success = models.BooleanField(default=True)
    error = models.TextField(blank=True, default='')

    @property
    def delay(self):
        if self.last_sync is None:
            return None
        # sanity check, this shouldn't happen
        if self.check_time < self.last_sync:
            return timedelta()
        return self.check_time - self.last_sync

    def __unicode__(self):
        return "Check of %s at %s" % (self.url.url, self.check_time)

    class Meta:
        verbose_name = 'mirror check log'
        get_latest_by = 'check_time'


for model in (Mirror, MirrorProtocol, MirrorUrl, MirrorRsync, CheckLocation):
    pre_save.connect(set_created_field, sender=model,
            dispatch_uid="mirrors.models")

# vim: set ts=4 sw=4 et:

mirrors/views/api.py
from datetime import timedelta
import json

from django.core.serializers.json import DjangoJSONEncoder
from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404
from django.utils.timezone import now

from ..models import (Mirror, MirrorUrl, MirrorProtocol, MirrorLog,
        CheckLocation)
from ..utils import get_mirror_statuses, DEFAULT_CUTOFF


class MirrorStatusJSONEncoder(DjangoJSONEncoder):
    '''Base JSONEncoder extended to handle datetime.timedelta and MirrorUrl
    serialization. The base class takes care of datetime.datetime types.'''
    url_attributes = ('url', 'protocol', 'last_sync', 'completion_pct',
            'delay', 'duration_avg', 'duration_stddev', 'score')

    def default(self, obj):
        if isinstance(obj, timedelta):
            # always returned as integer seconds
            return obj.days * 24 * 3600 + obj.seconds
        if isinstance(obj, MirrorUrl):
            data = {attr: getattr(obj, attr) for attr in self.url_attributes}
            country = obj.country
            data['country'] = unicode(country.name)
            data['country_code'] = country.code
            return data
        if isinstance(obj, MirrorProtocol):
            return unicode(obj)
        return super(MirrorStatusJSONEncoder, self).default(obj)


class ExtendedMirrorStatusJSONEncoder(MirrorStatusJSONEncoder):
    '''Adds URL check history information.'''
    log_attributes = ('check_time', 'last_sync', 'duration', 'is_success',
            'location_id')

    def default(self, obj):
        if isinstance(obj, MirrorUrl):
            data = super(ExtendedMirrorStatusJSONEncoder, self).default(obj)
            cutoff = now() - DEFAULT_CUTOFF
            data['logs'] = list(obj.logs.filter(
                    check_time__gte=cutoff).order_by('check_time'))
            return data
        if isinstance(obj, MirrorLog):
            data = {attr: getattr(obj, attr) for attr in self.log_attributes}
            data['error'] = obj.error or None
            return data
        return super(ExtendedMirrorStatusJSONEncoder, self).default(obj)


class LocationJSONEncoder(DjangoJSONEncoder):
    '''Base JSONEncoder extended to handle CheckLocation objects.'''

    def default(self, obj):
        if isinstance(obj, CheckLocation):
            return {
                'id': obj.pk,
                'hostname': obj.hostname,
                'source_ip': obj.source_ip,
                'country': unicode(obj.country.name),
                'country_code': obj.country.code,
                'ip_version': obj.ip_version,
            }
        return super(LocationJSONEncoder, self).default(obj)


def status_json(request, tier=None):
    if tier is not None:
        tier = int(tier)
        if tier not in [t[0] for t in Mirror.TIER_CHOICES]:
            raise Http404
    status_info = get_mirror_statuses()
    data = status_info.copy()
    if tier is not None:
        data['urls'] = [url for url in data['urls'] if url.mirror.tier == tier]
    data['version'] = 3
    to_json = json.dumps(data, ensure_ascii=False, cls=MirrorStatusJSONEncoder)
    response = HttpResponse(to_json, content_type='application/json')
    return response


def mirror_details_json(request, name):
    authorized = request.user.is_authenticated()
    mirror = get_object_or_404(Mirror, name=name)
    if not authorized and (not mirror.public or not mirror.active):
        raise Http404
    status_info = get_mirror_statuses(mirror_id=mirror.id,
            show_all=authorized)
    data = status_info.copy()
    data['version'] = 3
    to_json = json.dumps(data, ensure_ascii=False,
            cls=ExtendedMirrorStatusJSONEncoder)
    response = HttpResponse(to_json, content_type='application/json')
    return response


def locations_json(request):
    data = {}
    data['version'] = 1
    data['locations'] = list(CheckLocation.objects.all().order_by('pk'))
    to_json = json.dumps(data, ensure_ascii=False, cls=LocationJSONEncoder)
    response = HttpResponse(to_json, content_type='application/json')
    return response

# vim: set ts=4 sw=4 et:

templates/mirrors/error_table.html.jinja
<table id="errorlog_mirrors" class="results">
    <thead>
        <tr>
            <th>Mirror URL</th>
            <th>Protocol</th>
            <th>Country</th>
            <th>Error Message</th>
            <th>Last Occurred</th>
            <th>Occurrences (last {{ cutoff|hours }})</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for log in error_logs %}<tr class="{{ loop.cycle('odd', 'even') }}">
            <td>{{ log.url.url }}</td>
            <td>{{ log.url.protocol.protocol }}</td>
            <td class="country">{{ country_flag(log.url.country) }}{{ log.url.country.name }}</td>
            <td class="wrap">{{ log.error|linebreaksbr }}</td>
            <td>{{ log.last_occurred|date('Y-m-d H:i') }}</td>
            <td>{{ log.error_count }}</td>
            <td><a href="{{ log.url.get_absolute_url() }}">details</a></td>
        </tr>{% endfor %}
    </tbody>
</table>

templates/mirrors/mirror_details.html
{% extends "base.html" %}
{% load cycle from future %}
{% load static from staticfiles %}
{% load mirror_status %}
{% load flags %}
{% load admin_urls %}
{% load bugs %}

{% block title %}{{ BRANDING_DISTRONAME }} - {{ mirror.name }} - Mirror Details{% endblock %}

{% block head %}<link rel="stylesheet" type="text/css" href="{% static "flags/fam.css" %}" media="screen, projection" />{% endblock %}

{% block content %}
<div class="box">
    <h2>Mirror Details: {{ mirror.name }}</h2>

    {% if perms.mirrors.change_mirror %}
    <ul class="admin-actions">
        <li><a href="{% url 'admin:mirrors_mirror_change' mirror.pk %}" title="Edit mirror">Edit Mirror</a></li>
    </ul>
    {% endif %}

    <table class="compact">
        <tr>
            <th>Name:</th>
            <td>{{ mirror.name }}</td>
        </tr>
        <tr>
            <th>Tier:</th>
            <td>{{ mirror.get_tier_display }}</td>
        </tr>
        <tr>
            <th>Has ISOs:</th>
            <td>{{ mirror.isos|yesno|capfirst }}</td>
        </tr>
        {% if user.is_authenticated %}
        <tr>
            <th>Public:</th>
            <td>{{ mirror.public|yesno|capfirst }}</td>
        </tr>
        <tr>
            <th>Active:</th>
            <td>{{ mirror.active|yesno|capfirst }}</td>
        </tr>
        <tr>
            <th>Created:</th>
            <td>{{ mirror.created }}</td>
        </tr>
        <tr>
            <th>Last Modified:</th>
            <td>{{ mirror.last_modified }}</td>
        </tr>
        <tr>
            <th>Rsync IPs:</th>
            <td class="wrap">{{mirror.rsync_ips.all|join:', '}}</td>
        </tr>
        <tr>
            <th>Admin Email:</th>
            <td>{% if mirror.admin_email %}<a href="mailto:{{ mirror.admin_email }}">{{ mirror.admin_email }}</a>{% else %}None{% endif %}</td>
        </tr>
        <tr>
            <th>Alternate Email:</th>
            <td>{% if mirror.alternate_email %}<a href="mailto:{{ mirror.alternate_email }}">{{ mirror.alternate_email }}</a>{% else %}None{% endif %}</td>
        </tr>
        <tr>
            <th>Notes:</th>
            <td class="wrap">{{ mirror.notes|linebreaks }}</td>
        </tr>
        <tr>
            <th>Upstream:</th>
            <td>{% if mirror.upstream %}
                <a href="{{ mirror.upstream.get_absolute_url }}"
                    title="Mirror details for {{ mirror.upstream.name }}">{{ mirror.upstream.name }}</a>
                {% else %}None{% endif %}</td>
        </tr>
        <tr>
            <th>Downstream:</th>
            {% with mirror.downstream as ds_mirrors %}
            <td class="wrap">{% if ds_mirrors %}
                {% for ds in ds_mirrors %}
                <a href="{{ ds.get_absolute_url }}"
                    title="Mirror details for {{ ds.name }}">{{ ds.name }}</a>{% comment %}
                {% endcomment %}{% if not ds.active %} <span class="testing-dep">(inactive)</span>{% endif %}{% comment %}
                {% endcomment %}{% if not ds.public %} <span class="testing-dep">(private)</span>{% endif %}{% comment %}
                {% endcomment %}{% if not forloop.last %}, {% endif %}{% endfor %}
                {% else %}None{% endif %}</td>
            {% endwith %}
        </tr>
        {% endif %}
    </table>

    <h3>Available URLs</h3>
    {% include "mirrors/mirror_details_urls.html.jinja" %}

    <h3>Error Log</h3>
    {% include "mirrors/error_table.html.jinja" %}
</div>

<div class="box">
    <h2>Mirror Status Charts</h2>

    <p>Periodic checks of the mirrors are done from various geographic
    locations, IP addresses, and using IPv4 or IPv6. These results are
    summarized in graphical form below.</p>

    <div id="charts-container"></div>
</div>
{% endblock %}

{% block script_block %}
{% load cdn %}{% jquery %}{% jquery_tablesorter %}
<script type="text/javascript" src="{% static "d3-3.0.6.min.js" %}"></script>
<script type="text/javascript" src="{% static "hyperweb.js" %}"></script>
<script type="text/javascript" src="{% static "mirror_status.js" %}"></script>
<script type="text/javascript">
$(document).ready(function() {
    $("#available_urls:has(tbody tr)").tablesorter(
        {widgets: ['zebra'], sortList: [[1,0], [2,0]],
        headers: { 8: { sorter: 'mostlydigit' }, 9: { sorter: 'mostlydigit' }, 10: { sorter: 'mostlydigit' } } });
});
$(document).ready(function() {
    draw_graphs("/mirrors/locations/json/", "./json/", "#charts-container");
});
</script>
{% endblock %}

templates/mirrors/mirror_details_urls.html.jinja
<table id="available_urls" class="results">
    <thead>
        <tr>
            <th>Mirror URL</th>
            <th>Protocol</th>
            <th>Country</th>
            <th>IPv4</th>
            <th>IPv6</th>
            <th>Last Sync</th>
            <th>Completion %</th>
            <th>μ Delay (hh:mm)</th>
            <th>μ Duration (s)</th>
            <th>σ Duration (s)</th>
            <th>Score</th>
            <th>Details</th>
        </tr>
    </thead>
    <tbody>
        {% for m_url in urls %}
        <tr class="{{ loop.cycle('odd', 'even') }}">
            <td>{% if m_url.protocol.is_download %}<a href="{{ m_url.url }}">{{ m_url.url }}</a>{% else %}{{ m_url.url }}{% endif %}</td>
            <td>{{ m_url.protocol }}</td>
            <td class="country">{{ country_flag(m_url.country) }}{{ m_url.country.name }}</td>
            <td>{{ m_url.has_ipv4|yesno|capfirst }}</td>
            <td>{{ m_url.has_ipv6|yesno|capfirst }}</td>
            <td>{{ m_url.last_sync|date('Y-m-d H:i')|default('unknown') }}</td>
            <td>{{ m_url.completion_pct|percentage(1) }}</td>
            <td>{{ m_url.delay|duration|default('unknown') }}</td>
            <td>{{ m_url.duration_avg|floatvalue(2) }}</td>
            <td>{{ m_url.duration_stddev|floatvalue(2) }}</td>
            <td>{{ m_url.score|floatvalue(1)|default('∞') }}</td>
            <td><a href="{{ m_url.id }}/">Details</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

templates/mirrors/mirrorlist_generate.html
{% extends "base.html" %}
{% load package_extras %}
{% load wiki %}
{% block title %}{{ BRANDING_DISTRONAME }} - Pacman Mirrorlist Generator{% endblock %}

{% block content %}
<div id="mirrorlist-gen" class="box">

    <h2>Pacman Mirrorlist Generator</h2>

    <p>This page generates the most up-to-date mirrorlist possible for {{ BRANDING_DISTRONAME }}.
    The data used here comes straight from the developers' internal
    mirror database used to track mirror availability and tiering. There are
    two main options: get a mirrorlist with every available mirror, or get a
    mirrorlist tailored to your geography.</p>

    <h3>Mirrorlist with all available mirrors</h3>

    <p>An up-to-date mirrorlist is available containing all currently active
    mirrors, optionally filtering by protocol. These URLs requires no GET or
    POST parameters so they can be fetched from the command line if desired.<p>

    <ul>
        <li><a href="all/">All mirrors</a></li>
        <li><a href="all/http/">All mirrors, HTTP only</a></li>
        <li><a href="all/https/">All mirrors, HTTPS only</a></li>
    </ul>

    <h3>Customized by country mirrorlist</h3>

    <p>The following form can generate a custom up-to-date
    <a href="{% wiki_url 'Pacman' %}"
        title="{{BRANDING_WIKINAME}}: Pacman">pacman</a> mirrorlist based on geography and
    desired protocol(s).  Simply replace the contents of
    <code>/etc/pacman.d/mirrorlist</code> with your generated list.
    Additionally, the mirror status data can be incorporated into the generated
    mirror list and used to pre-order the mirrors.</p>

    <form id="list-generator" method="get">
        {{ mirrorlist_form.as_div }}
        <p><label></label> <input type="submit" value="Generate List" /></p>
    </form>
</div>
{% endblock %}

templates/mirrors/mirrors.html
{% extends "base.html" %}
{% load cycle from future %}
{% load static from staticfiles %}
{% load flags %}

{% block title %}{{ BRANDING_DISTRONAME }} - Mirror Overview{% endblock %}

{% block head %}<link rel="stylesheet" type="text/css" href="{% static "flags/fam.css" %}" media="screen, projection" />{% endblock %}

{% block content %}
<div id="dev-mirrorlist" class="box">
    <h2>Mirror Overview</h2>
    <table class="results">
        <thead>
            <tr>
                <th>Server</th>
                <th>Country</th>
                <th>Tier</th>
                <th>ISOs</th>
                <th>Protocols</th>
                {% if user.is_authenticated %}
                <th>Public</th>
                <th>Active</th>
                <th>Admin Email</th>
                <th>Notes</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for mirror in mirror_list %}
            <tr class="{% cycle 'odd' 'even' %}">
                <td><a href="{{ mirror.get_absolute_url }}"
                        title="Mirror details for {{ mirror.name }}">{{ mirror.name }}</a></td>
                <td class="country">{% if mirror.country %}{% country_flag mirror.country %}{{ mirror.country.name }}{% else %}Various{% endif %}</td>
                <td>{{ mirror.get_tier_display }}</td>
                <td>{{ mirror.isos|yesno|capfirst }}</td>
                <td class="wrap">{{ mirror.protocols|join:", " }}</td>
                {% if user.is_authenticated %}
                <td>{{ mirror.public|yesno|capfirst }}</td>
                <td>{{ mirror.active|yesno|capfirst }}</td>
                <td>{{ mirror.admin_email }}</td>
                <td class="wrap">{{ mirror.notes|linebreaks }}</td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% load cdn %}{% jquery %}{% jquery_tablesorter %}
<script type="text/javascript" src="{% static "hyperweb.js" %}"></script>
<script type="text/javascript">
$(document).ready(function() {
    $(".results").tablesorter({widgets: ['zebra'], sortList: [[2,0], [0,0]]});
});
</script>
{% endblock %}