devel/urls.py
from django.conf.urls import patterns

urlpatterns = patterns('devel.views',
    (r'^admin_log/$','admin_log'),
    (r'^admin_log/(?P<username>.*)/$','admin_log'),
    (r'^clock/$',    'clock', {},     'devel-clocks'),
    (r'^$',          'index', {},     'devel-index'),
    (r'^stats/$',    'stats', {},     'devel-stats'),
    (r'^newuser/$',  'new_user_form'),
    (r'^profile/$',  'change_profile'),
    (r'^reports/(?P<report_name>.*)/(?P<username>.*)/$', 'report'),
    (r'^reports/(?P<report_name>.*)/$', 'report'),
)

# vim: set ts=4 sw=4 et:

urls.py
from django.conf.urls import include, patterns, url
from django.contrib import admin

from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView, RedirectView

from feeds import PackageFeed, NewsFeed, ReleaseFeed

urlpatterns = []

# Public pages
urlpatterns += patterns('public.views',
    (r'^$', 'index', {}, 'index'),
    (r'^about/$', TemplateView.as_view(template_name='public/about.html'),
        {}, 'page-about'),
    (r'^art/$', RedirectView.as_view(url='https://git.hyperbola.info:50100/culture'),
        {}, 'page-art'),
    (r'^donate/$', RedirectView.as_view(url='https://wiki.hyperbola.info/Donations'),
        {}, 'page-donate'),
    (r'^download/$', RedirectView.as_view(url='https://wiki.hyperbola.info/Get_Hyperbola'),
        {}, 'page-download'),
    (r'^master-keys/$',  'keys',     {}, 'page-keys'),
    (r'^master-keys/json/$', 'keys_json', {}, 'pgp-keys-json'),
    (r'^members/(?P<slug>[-\w]+)/$', 'members', {}, 'members'),
)

# Feeds patterns, used below
feeds_patterns = patterns('',
    (r'^$',          'public.views.feeds', {}, 'feeds-list'),
    (r'^news/$',     cache_page(311)(NewsFeed())),
    (r'^packages/$', cache_page(313)(PackageFeed())),
    (r'^packages/(?P<arch>[A-z0-9]+)/$',
        cache_page(313)(PackageFeed())),
    (r'^packages/all/(?P<repo>[A-z0-9\-]+)/$',
        cache_page(313)(PackageFeed())),
    (r'^packages/(?P<arch>[A-z0-9]+)/(?P<repo>[A-z0-9\-]+)/$',
        cache_page(313)(PackageFeed())),
    (r'^releases/$', cache_page(317)(ReleaseFeed())),
)

# Includes and other remaining stuff
urlpatterns += patterns('',
    (r'^admin/',     include(admin.site.urls)),
    (r'^devel/',     include('devel.urls')),
    (r'^feeds/',     include(feeds_patterns)),
    (r'^groups/',    include('packages.urls_groups')),
    (r'^mirrorlist/',include('mirrors.urls_mirrorlist')),
    (r'^mirrors/',   include('mirrors.urls')),
    (r'^news/',      include('news.urls')),
    (r'^packages/',  include('packages.urls')),
    (r'^releng/',    include('releng.urls')),
    (r'^todo/',      include('todolists.urls')),
    (r'^visualize/', include('visualize.urls')),
    (r'^opensearch/packages/$', 'packages.views.opensearch',
        {}, 'opensearch-packages'),
    (r'^opensearch/packages/suggest$', 'packages.views.opensearch_suggest',
        {}, 'opensearch-packages-suggest'),
)

# Authentication
urlpatterns += patterns('django.contrib.auth.views',
    (r'^login/$', 'login', {'template_name': 'registration/login.html'}, 'login'),
    (r'^logout/$', 'logout', {'template_name': 'registration/logout.html'}, 'logout'),
)

# Redirects for older known pages we see in the logs
legacy_urls = (
    ('^about.php',     '/about/'),
    ('^changelog.php', '/packages/?sort=-last_update'),
    ('^devs.php',      '/members/developers/'),
    ('^donations.php', '/donate/'),
    ('^download.php',  '/download/'),
    ('^index.php',     '/'),
    ('^logos.php',     '/logotypes/'),
    ('^news.php',      '/news/'),
    ('^packages.php',  '/packages/'),
    ('^members.php',    '/members/'),
    ('^todolists/$',   '/todo/'),
    ('^developers/$',  '/members/developers/'),
    ('^artists/$',     '/members/artists/'),
    ('^fellows/$',     '/members/member-fellows/'),
    ('^trustedusers/$', '/members/trustedusers/'),

    ('^docs/en/guide/install/arch-install-guide.html',
        'https://wiki.hyperbola.info/Installation_Guide'),
    ('^docs/en/', 'https://wiki.hyperbola.info/'),
    ('^docs/', 'https://wiki.hyperbola.info/'),
)

urlpatterns += [url(old_url, RedirectView.as_view(url=new_url))
        for old_url, new_url in legacy_urls]


def show_urls(urllist=urlpatterns, depth=0):
    for entry in urllist:
        print "  " * depth, entry.regex.pattern
        if hasattr(entry, 'url_patterns'):
            show_urls(entry.url_patterns, depth + 1)

# vim: set ts=4 sw=4 et:

devel/models.py
# -*- coding: utf-8 -*-
import pytz

from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import pre_save
from django.contrib.auth.models import User, Group
from django_countries.fields import CountryField

from .fields import PGPKeyField
from main.utils import make_choice, set_created_field


class UserProfile(models.Model):
    notify = models.BooleanField(
        "Send notifications",
        default=True,
        help_text="When enabled, send user 'flag out-of-date' notifications")
    time_zone = models.CharField(
        max_length=100,
        choices=make_choice(pytz.common_timezones),
        default="UTC",
        help_text="Used for developer clock page")
    alias = models.CharField(
        max_length=50,
        help_text="Required field")
    public_email = models.CharField(
        max_length=50,
        help_text="Required field")
    other_contact = models.CharField(max_length=100, null=True, blank=True)
    pgp_key = PGPKeyField(max_length=40, null=True, blank=True,
        verbose_name="PGP key fingerprint",
        help_text="consists of 40 hex digits; use `gpg --fingerprint`")
    website = models.CharField(max_length=200, null=True, blank=True)
    yob = models.IntegerField("Year of birth", null=True, blank=True)
    country = CountryField(blank=True)
    location = models.CharField(max_length=50, null=True, blank=True)
    languages = models.CharField(max_length=50, null=True, blank=True)
    interests = models.CharField(max_length=255, null=True, blank=True)
    occupation = models.CharField(max_length=50, null=True, blank=True)
    roles = models.CharField(max_length=255, null=True, blank=True)
    favorite_distros = models.CharField(max_length=255, null=True, blank=True)
    picture = models.FileField(upload_to='devs', default='devs/silhouette.png',
        help_text="Ideally 125px by 125px")
    user = models.OneToOneField(User, related_name='userprofile')
    allowed_repos = models.ManyToManyField('main.Repo', blank=True)
    latin_name = models.CharField(max_length=255, null=True, blank=True,
        help_text="Latin-form name; used only for non-Latin full names")
    last_modified = models.DateTimeField(editable=False)

    class Meta:
        db_table = 'user_profiles'
        get_latest_by = 'last_modified'
        verbose_name = 'additional profile data'
        verbose_name_plural = 'additional profile data'

    def get_absolute_url(self):
        user = self.user
        group = StaffGroup.objects.filter(group=user.groups.all()).first()
        if group:
            return '%s#%s' % (group.get_absolute_url(), user.username)
        return None


class StaffGroup(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)
    group = models.OneToOneField(Group)
    sort_order = models.PositiveIntegerField()
    member_title = models.CharField(max_length=100)
    description = models.TextField(blank=True)

    class Meta:
        ordering = ('sort_order',)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('member', args=[self.slug])


class MasterKey(models.Model):
    owner = models.ForeignKey(User, related_name='masterkey_owner',
        help_text="The developer holding this master key")
    revoker = models.ForeignKey(User, related_name='masterkey_revoker',
        help_text="The developer holding the revocation certificate")
    pgp_key = PGPKeyField(max_length=40, verbose_name="PGP key fingerprint",
        help_text="consists of 40 hex digits; use `gpg --fingerprint`")
    created = models.DateField()
    revoked = models.DateField(null=True, blank=True)

    class Meta:
        ordering = ('created',)
        get_latest_by = 'created'

    def __unicode__(self):
        return u'%s, created %s' % (
                self.owner.get_full_name(), self.created)


class DeveloperKey(models.Model):
    owner = models.ForeignKey(User, related_name='all_keys', null=True,
            help_text="The developer this key belongs to")
    key = PGPKeyField(max_length=40, verbose_name="PGP key fingerprint",
            unique=True)
    created = models.DateTimeField()
    expires = models.DateTimeField(null=True, blank=True)
    revoked = models.DateTimeField(null=True, blank=True)
    parent = models.ForeignKey('self', null=True, on_delete=models.SET_NULL)

    def __unicode__(self):
        return self.key


class PGPSignature(models.Model):
    signer = PGPKeyField(max_length=40, verbose_name="Signer key fingerprint",
            db_index=True)
    signee = PGPKeyField(max_length=40, verbose_name="Signee key fingerprint",
            db_index=True)
    created = models.DateField()
    expires = models.DateField(null=True, blank=True)
    revoked = models.DateField(null=True, blank=True)

    class Meta:
        ordering = ('signer', 'signee')
        get_latest_by = 'created'
        verbose_name = 'PGP signature'

    def __unicode__(self):
        return u'%s → %s' % (self.signer, self.signee)


pre_save.connect(set_created_field, sender=UserProfile,
        dispatch_uid="devel.models")

# vim: set ts=4 sw=4 et:

devel/forms.py
import random
from collections import OrderedDict
from string import ascii_letters, digits

from django import forms
from django.conf import settings
from django.contrib.auth.models import User, Group
from django.contrib.sites.models import Site
from django.core.mail import send_mail
from django.template import loader, Context

from .models import UserProfile


class ProfileForm(forms.Form):
    email = forms.EmailField(label='Private email (not shown publicly):',
            help_text="Used for out-of-date notifications, etc.")
    passwd1 = forms.CharField(label='New Password', required=False,
            widget=forms.PasswordInput)
    passwd2 = forms.CharField(label='Confirm Password', required=False,
            widget=forms.PasswordInput)

    def clean(self):
        if self.cleaned_data['passwd1'] != self.cleaned_data['passwd2']:
            raise forms.ValidationError('Passwords do not match.')
        return self.cleaned_data


class UserProfileForm(forms.ModelForm):
    def clean_pgp_key(self):
        data = self.cleaned_data['pgp_key']
        # strip 0x prefix if provided; store uppercase
        if data.startswith('0x'):
            data = data[2:]
        return data.upper()

    class Meta:
        model = UserProfile
        exclude = ('allowed_repos', 'user', 'latin_name')


class NewUserForm(forms.ModelForm):
    username = forms.CharField(max_length=30)
    private_email = forms.EmailField()
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)
    groups = forms.ModelMultipleChoiceField(required=False,
            queryset=Group.objects.all())

    class Meta:
        model = UserProfile
        exclude = ('picture', 'user')

    def __init__(self, *args, **kwargs):
        super(NewUserForm, self).__init__(*args, **kwargs)
        # Hack ourself so certain fields appear first
        old = self.fields
        self.fields = OrderedDict()
        keys = ('username', 'private_email', 'first_name', 'last_name',
                'alias', 'public_email')
        for key in keys:
            self.fields[key] = old[key]
        for key, val in old.items():
            if key not in keys:
                self.fields[key] = old[key]

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError(
                    "A user with that username already exists.")
        return username

    def save(self, commit=True):
        profile = super(NewUserForm, self).save(False)
        pwletters = ascii_letters + digits
        password = ''.join([random.choice(pwletters) for _ in xrange(8)])
        user = User.objects.create_user(username=self.cleaned_data['username'],
                email=self.cleaned_data['private_email'], password=password)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.save()
        # sucks that the MRM.add() method can't take a list directly... we have
        # to resort to dirty * magic.
        user.groups.add(*self.cleaned_data['groups'])
        profile.user = user
        if commit:
            profile.save()
            self.save_m2m()

        template = loader.get_template('devel/new_account.txt')
        ctx = Context({
            'site': Site.objects.get_current(),
            'user': user,
            'password': password,
        })

        send_mail("Your new hyperweb account",
                template.render(ctx),
                settings.BRANDING_EMAIL,
                [user.email],
                fail_silently=False)

# vim: set ts=4 sw=4 et:

templates/devel/admin_log.html
{% extends "admin/base_site.html" %}
{% load i18n admin_static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/dashboard.css" %}" />{% endblock %}

{% block breadcrumbs %}<div class="breadcrumbs"><a href="/admin/">{% trans 'Home' %}</a>{% if title %} &rsaquo; {{ title }}{% endif %}</div>{% endblock %}

{% block content %}
<div id="content-main">
    <div class="module">
{% load log %}
{% if log_user %}
{% get_admin_log 100 as admin_log for_user log_user %}
{% else %}
{% get_admin_log 100 as admin_log %}
{% endif %}
{% if not admin_log %}
<p>{% trans 'None available' %}</p>
{% else %}
<table id="change-history">
    <thead>
        <tr>
            <th scope="col">{% trans 'Date/time' %}</th>
            <th scope="col">{% trans 'User' %}</th>
            <th>Type</th>
            <th>Object</th>
            <th scope="col">{% trans 'Action' %}</th>
        </tr>
    </thead>
    <tbody>
        {% for entry in admin_log %}
        <tr>
            <th scope="row">{{ entry.action_time|date:"DATETIME_FORMAT" }}</th>
            {% if log_user %}
            <td>{{ entry.user.username }}{% if entry.user.get_full_name %} ({{ entry.user.get_full_name }}){% endif %}</td>
            {% else %}
            <td><a href="{{ entry.user.username }}/">{{ entry.user.username }}</a>{% if entry.user.get_full_name %} ({{ entry.user.get_full_name }}){% endif %}</td>
            {% endif %}
            <td>
                {% if entry.content_type %}
                <span>{% filter capfirst %}{% trans entry.content_type.name %}{% endfilter %}</span>
                {% else %}
                <span>{% trans 'Unknown content' %}</span>
                {% endif %}
            </td>
            <td>
                <span class="{% if entry.is_addition %}addlink{% endif %}{% if entry.is_change %}changelink{% endif %}{% if entry.is_deletion %}deletelink{% endif %}"></span>
                {% if entry.is_deletion %}
                {{ entry.object_repr }}
                {% else %}
                <a href="{{ entry.get_admin_url }}">{{ entry.object_repr }}</a>
                {% endif %}
            </td>
            <td>{{ entry.change_message }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endif %}
    </div>
</div>
{% endblock %}

templates/devel/clock.html
{% extends "base.html" %}
{% load cycle from future %}
{% load static from staticfiles %}
{% load flags %}
{% load tz %}

{% block title %}{{ BRANDING_DISTRONAME }} - Member World Clocks{% endblock %}

{% block head %}<link rel="stylesheet" type="text/css" href="{% static "flags/fam.css" %}" media="screen, projection" />{% endblock %}

{% block content %}
<div id="dev-clocks-box" class="box">
    <h2>Member World Clocks</h2>

    <p>This page helps prevent you from waking a sleeping member. It also
    depends on members keeping the time zone information up to date, so if
    you see 'UTC' listed, pester them to update their settings.</p>
    <p>The "Last Action" column shows the last time this member has done
    something we know about. Considered dates for each member include:</p>
    <ul>
        <li>Build date of a package in the repositories</li>
        <li>Last login to the member side of this site</li>
        <li>Admin log entry on this site (e.g., adding a donor, modifying a
        mirror)</li>
        <li>Post date of a news item</li>
        <li>Signing off on a package</li>
        <li>Flagging a package out-of-date</li>
    </ul>
    <p>
    Current UTC Time: {{ utc_now|date:"Y-m-d H:i T" }}
    </p>

    <table id="clocks-table" class="results">
        <thead>
            <tr>
                <th>Member</th>
                <th>Username</th>
                <th>Alias</th>
                <th>Last Action</th>
                <th>Location</th>
                <th>Time Zone</th>
                <th>Current Time</th>
            </tr>
        </thead>
        <tbody>
            {% for dev in members %}
            <tr class="{% cycle 'odd' 'even' %}">
                <td><a href="mailto:{{ dev.email }}">{{ dev.get_full_name }}</a></td>
                <td>{{ dev.username }}</td>
                <td>{{ dev.userprofile.alias }}</td>
                <td>{{ dev.last_action }}</td>
                <td>{% country_flag dev.userprofile.country %}{{ dev.userprofile.location }}</td>
                <td>{{ dev.userprofile.time_zone }}</td>
                <td>{{ utc_now|timezone:dev.userprofile.time_zone|date:"Y-m-d H:i T" }}<span class="hide"> {{ dev.userprofile.time_zone }}</span></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

{% block script_block %}
{% load cdn %}{% jquery %}{% jquery_tablesorter %}
<script type="text/javascript" src="{% static "hyperweb.js" %}"></script>
<script type="text/javascript">
$(document).ready(function() {
    $("#clocks-table:has(tbody tr)").tablesorter({
        widgets: ['zebra'],
        sortLocaleCompare: true,
        sortList: [[0,0]],
        headers: { 4: { sorter: false } }
    });
});
</script>
{% endblock %}

templates/devel/index.html
{% extends "base.html" %}
{% load cycle from future %}
{% load static from staticfiles %}
{% load cache %}
{% load package_extras %}
{% load todolists %}

{% block title %}{{ BRANDING_DISTRONAME }} - Developer Dashboard{% endblock %}

{% block content %}
<div id="dev-dashboard" class="box">

    <h2>Developer Dashboard</h2>

    <h3>My Flagged Packages</h3>

    <table id="dash-myflagged" class="results">
        <thead>
            <tr>
                <th>Name</th>
                <th>Version</th>
                <th>Testing Version</th>
                <th>Repo</th>
                <th>Arch</th>
                <th>Flagged</th>
                <th>Last Updated</th>
            </tr>
        </thead>
        <tbody>
            {% for pkg in flagged %}
                <tr class="{% cycle 'odd' 'even' %}">
                    <td>{% pkg_details_link pkg %}</td>
                    <td>{{ pkg.full_version }}</td>
                    <td>{% with pkg.in_testing as tp %}{% if tp %}
                        <a href="{{ tp.get_absolute_url }}"
                            title="Testing package details for {{ tp.pkgname }}">{{ tp.full_version }}</a>
                        {% endif %}{% endwith %}</td>
                    <td>{{ pkg.repo.name }}</td>
                    <td>{{ pkg.arch.name }}</td>
                    <td>{{ pkg.flag_date|date }}</td>
                    <td>{{ pkg.last_update|date }}</td>
                </tr>
            {% empty %}
                <tr class="empty"><td colspan="7"><em>No flagged packages to display</em></td></tr>
            {% endfor %}
        </tbody>
    </table>

    <h3>My Incomplete Todo List Packages</h3>

    <table id="dash-mytodolist" class="results">
        <thead>
            <tr>
                <th>Todo List</th>
                <th>Name</th>
                <th>Repo</th>
                <th>Arch</th>
                <th>Maintainer(s)</th>
            </tr>
        </thead>
        <tbody>
            {% for todopkg in todopkgs %}
                <tr class="{% cycle 'odd' 'even' %}">
                    <td><a href="{{ todopkg.todolist.get_absolute_url }}"
                            title="View todo list: {{ todopkg.todolist.name }}">{{ todopkg.todolist.name }}</a></td>
                    <td>{% todopkg_details_link todopkg %}</td>
                    <td>{{ todopkg.repo.name }}</td>
                    <td>{{ todopkg.arch.name }}</td>
                    <td>{{ todopkg.pkg.maintainers|join:', ' }}</td>
                </tr>
            {% empty %}
                <tr class="empty"><td colspan="5"><em>No incomplete todo list packages to display</em></td></tr>
            {% endfor %}
        </tbody>
    </table>

    <h3>Package Todo Lists</h3>

    <table id="dash-todo" class="results">
        <thead>
            <tr>
                <th>Name</th>
                <th>Creation Date</th>
                <th>Creator</th>
                <th>Description</th>
                <th>Package Count</th>
                <th>Incomplete Count</th>
            </tr>
        </thead>
        <tbody>
            {% for todo in todos %}
            <tr class="{% cycle 'odd' 'even' %}">
                <td><a href="{{ todo.get_absolute_url }}"
                        title="View todo list: {{ todo.name }}">{{ todo.name }}</a></td>
                <td>{{ todo.created|date }}</td>
                <td>{{ todo.creator.get_full_name }}</td>
                <td class="wrap">{{ todo.description|urlize }}</td>
                <td>{{ todo.pkg_count }}</td>
                <td>{{ todo.incomplete_count }}</td>
            </tr>
            {% empty %}
            <tr class="empty"><td colspan="6"><em>No package todo lists to display</em></td></tr>
            {% endfor %}
        </tbody>
    </table>

    <h3>Signoff Status</h3>

    <table id="dash-signoffs" class="results">
        <thead>
            <tr>
                <th>Name</th>
                <th>Version</th>
                <th>Arch</th>
                <th>Target Repo</th>
                <th>Last Updated</th>
                <th>Approved</th>
                <th>Signoffs</th>
            </tr>
        </thead>
        <tbody>
            {% for group in signoffs %}
            <tr class="{% cycle 'odd' 'even' %}">
                <td>{% pkg_details_link group.package %}</td>
                <td>{{ group.version }}</td>
                <td>{{ group.arch.name }}</td>
                <td>{{ group.target_repo }}</td>
                <td>{{ group.last_update|date }}</td>
                {% if group.specification.known_bad %}
                <td class="approval signoff-bad">Bad</td>
                {% else %}
                {% if not group.specification.enabled %}
                <td class="approval signoff-disabled">Disabled</td>
                {% else %}
                <td class="approval signoff-{{ group.approved|yesno }}">{{ group.approved|yesno|capfirst }}</td>
                {% endif %}
                {% endif %}
                <td><ul class="signoff-list">
                    {% for signoff in group.signoffs %}
                    <li class="signed-username" title="Signed off by {{ signoff.user }}">{{ signoff.user }}{% if signoff.revoked %} (revoked){% endif %}</li>
                    {% endfor %}
                </ul></td>
            </tr>
            {% empty %}
            <tr class="empty"><td colspan="7"><em>No packages you maintain or have packaged need signoffs</em></td></tr>
            {% endfor %}
        </tbody>
    </table>

    <h3>Developer Reports</h3>
    <ul>
        {% for report in reports %}
        <li><a href="reports/{{ report.slug }}/">{{ report.name }}</a>:
        {{ report.description }}
        {% if report.personal %}(<a href="reports/{{ report.slug }}/{{ user.username }}/">yours only</a>){% endif %}</li>
        {% endfor %}
    </ul>
</div>{# #dev-dashboard #}

<div id="stats-area">
    <div class="box">
        <h2>Developer Stats</h2>
        <p id="stats-message">Enable JavaScript to get more useful info here.</p>
    </div>
</div>
{% endblock %}

{% block script_block %}
{% load cdn %}{% jquery %}{% jquery_tablesorter %}
<script type="text/javascript" src="{% static "hyperweb.js" %}"></script>
<script type="text/javascript">
$(document).ready(function() {
    $("#stats-message").html('Loading developer stats…');
    $("#stats-area").load('stats/', function(response, status, xhr) {
        if (status === 'error' || status === 'timeout') {
            $("#stats-message").html('Developer stats loading encountered an error. Sorry.');
            return;
        }
        var settings = {
            widgets: ['zebra'],
            sortList: [[0,0]],
            headers: { 1: { sorter: 'pkgcount' }, 2: { sorter: 'pkgcount' }, 3: { sorter: 'pkgcount' } }
        };

        $(".dash-stats").not($("#stats-by-maintainer")).tablesorter(settings);
        settings['sortLocaleCompare'] = true;
        $("#stats-by-maintainer").tablesorter(settings);
    });

    $("#dash-myflagged:not(:has(tbody tr.empty))").tablesorter(
        {widgets: ['zebra'], sortList: [[0,0]]});
    $("#dash-mytodolist:not(:has(tbody tr.empty))").tablesorter(
        {widgets: ['zebra'], sortList: [[0,0], [1,0]]});
    $("#dash-todo:not(:has(tbody tr.empty))").tablesorter(
            {widgets: ['zebra'], sortList: [[1,1]]});
    $("#dash-signoffs:not(:has(tbody tr.empty))").tablesorter({
            widgets: ['zebra'],
            sortList: [[0,0]],
            headers: { 6: {sorter: false } }
    });
});
</script>
{% endblock %}

templates/devel/profile.html
{% extends "base.html" %}
{% load static from staticfiles %}

{% block title %}{{ BRANDING_DISTRONAME }} - Edit Profile{% endblock %}

{% block content %}
<div id="dev-edit-profile" class="box">

    <h2>Developer Profile</h2>

    <form id="edit-profile-form" enctype="multipart/form-data" method="post" action="">{% csrf_token %}
        <p><em>Note:</em> This is the public information shown on the developer
        and/or TU profiles page, so please be appropriate with the information
        you provide here.</p>
        <fieldset>
            <p><label>Username:</label>
            <strong>{{ user.username }}</strong></p>
            {{ form.as_p }}
        </fieldset>
        <fieldset>
            {{ profile_form.as_p }}
        </fieldset>
        <p><label></label> <input title="Save changes" type="submit" value="Save" /></p>
    </form>

</div>
{% endblock %}

{% block script_block %}
{% load cdn %}{% jquery %}
<script type="text/javascript" src="{% static "hyperweb.js" %}"></script>
<script type="text/javascript">
    modify_attributes({
        '#id_email': {type: 'email'},
        '#id_alias': {autocorrect: 'off', autocapitalize: 'off'},
        '#id_public_email': {autocorrect: 'off', autocapitalize: 'off'},
        '#id_website': {type: 'url'},
        '#id_yob': {pattern: '[0-9]*'}
    });
</script>
{% endblock %}